name: quick_eats_delivery_boy
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any

  cupertino_icons: ^1.0.5
  get_it: ^8.0.3
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  dio: ^5.1.1
  google_maps_flutter: ^2.2.5
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  url_launcher: ^6.1.11
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0
  path_provider: ^2.0.14
  vibration: ^3.1.3
  shimmer: ^3.0.0
  flutter_widget_from_html_core: ^0.16.0
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_lints: ^5.0.0
  http: ^1.2.1
  phone_numbers_parser: ^9.0.3
  country_code_picker: ^3.0.0
  dotted_border: ^2.0.0+3
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.10+1
  audioplayers: ^6.1.0
  flutter_foreground_task: ^8.13.0
  disable_battery_optimization: ^1.1.1






dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/
    - assets/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
